
//! Autogenerated weights for `pallet_gear_program`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-03-14, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("local"), DB CACHE: 1024

// Executed Command:
// ./target/release/gear-node benchmark --chain=local --execution=wasm --wasm-execution=compiled --pallet=pallet_gear_program --steps 50 --repeat 20 --output ./pallets/gear-program/src/weights/ --extrinsic=*

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(clippy::unnecessary_cast)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for `pallet_gear_program`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> super::WeightInfo for SubstrateWeight<T> {
	// Storage: GearProgram PausedPrograms (r:1 w:1)
	// Storage: System Account (r:2 w:2)
	// Storage: unknown [0x673a3a70616765733a3a13614ad1183876953cdd99749d6dcf5d41b7ffc0740c] (r:0 w:1)
	// Storage: unknown [0x673a3a70726f673a3a13614ad1183876953cdd99749d6dcf5d41b7ffc0740cd2] (r:0 w:1)
	// Storage: unknown [0x673a3a70726f675f776169743a3a13614ad1183876953cdd99749d6dcf5d41b7] (r:0 w:1)
	fn resume_program(q: u32, ) -> Weight {
		(0 as Weight)
			// Standard Error: 249_000
			.saturating_add((133_779_000 as Weight).saturating_mul(q as Weight))
			.saturating_add(T::DbWeight::get().reads(3 as Weight))
			.saturating_add(T::DbWeight::get().writes(5 as Weight))
			.saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(q as Weight)))
	}
}
