name: install-rust

runs:
  using: composite
  steps:
    - run: |
        Invoke-WebRequest -OutFile rustup-init.exe https://win.rustup.rs/x86_64
        .\rustup-init.exe -y --profile minimal
        Remove-Item rustup-init.exe
        Resolve-Path "~/.cargo/bin" >> $Env:GITHUB_PATH
      if: ${{ runner.os == 'Windows' }}
      shell: powershell

    - uses: dsherret/rust-toolchain-file@v1

    - name: "Install: Rust stable toolchain"
      run: rustup toolchain install stable --profile minimal
      shell: bash

    - name: "Select: Rust toolchain"
      run: |
        toolchain="$(sed -n 's/^channel = "\(.*\)"/\1/p' rust-toolchain.toml)"
        test -n "$toolchain"
        rustup default "$toolchain"
      shell: bash
