name: Feature
description: New functionality or improvement
labels: ["type: feat"]

body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      placeholder: What problem are we solving?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      placeholder: How should it work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      placeholder: Optional
