// Copyright (C) Gear Technologies Inc.
// SPDX-License-Identifier: GPL-3.0-or-later WITH Classpath-exception-2.0

//! Autogenerated weights for pallet_gear_voucher
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 43.0.0
//! DATE: 2026-05-25, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! CPU: `INTEL(R) XEON(R) GOLD 6526Y`
//! EXECUTION: , WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 1024

// Executed Command:
// ./target/production/gear benchmark pallet --runtime=./target/production/wbuild/vara-runtime/vara_runtime.compact.compressed.wasm --genesis-builder=runtime --genesis-builder-preset=development --steps=50 --repeat=20 --pallet=pallet_gear_voucher --extrinsic=* --heap-pages=16384 --output=./scripts/benchmarking/weights-output/pallet_gear_voucher.rs --template=scripts/benchmarking/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(clippy::unnecessary_cast)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_gear_voucher.
pub trait WeightInfo {
    fn issue() -> Weight;
    fn revoke() -> Weight;
    fn update() -> Weight;
    fn decline() -> Weight;
}

/// Weights for pallet_gear_voucher using the Gear node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    fn issue() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `282`
        //  Estimated: `6196`
        // Minimum execution time: 37_781_000 picoseconds.
        Weight::from_parts(39_827_000, 6196)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(4_u64))
    }
    fn revoke() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `543`
        //  Estimated: `6196`
        // Minimum execution time: 43_185_000 picoseconds.
        Weight::from_parts(46_040_000, 6196)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    fn update() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `1057`
        //  Estimated: `6196`
        // Minimum execution time: 43_014_000 picoseconds.
        Weight::from_parts(46_419_000, 6196)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }
    fn decline() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `300`
        //  Estimated: `3765`
        // Minimum execution time: 12_032_000 picoseconds.
        Weight::from_parts(13_682_000, 3765)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
}

// For backwards compatibility and tests
impl WeightInfo for () {
    fn issue() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `282`
        //  Estimated: `6196`
        // Minimum execution time: 37_781_000 picoseconds.
        Weight::from_parts(39_827_000, 6196)
            .saturating_add(RocksDbWeight::get().reads(3_u64))
            .saturating_add(RocksDbWeight::get().writes(4_u64))
    }
    fn revoke() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `543`
        //  Estimated: `6196`
        // Minimum execution time: 43_185_000 picoseconds.
        Weight::from_parts(46_040_000, 6196)
            .saturating_add(RocksDbWeight::get().reads(3_u64))
            .saturating_add(RocksDbWeight::get().writes(2_u64))
    }
    fn update() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `1057`
        //  Estimated: `6196`
        // Minimum execution time: 43_014_000 picoseconds.
        Weight::from_parts(46_419_000, 6196)
            .saturating_add(RocksDbWeight::get().reads(3_u64))
            .saturating_add(RocksDbWeight::get().writes(3_u64))
    }
    fn decline() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `300`
        //  Estimated: `3765`
        // Minimum execution time: 12_032_000 picoseconds.
        Weight::from_parts(13_682_000, 3765)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
}
