FROM debian:12-slim

ARG RELEASE_VERSION

RUN apt-get update && \
    apt-get install -y curl sudo xz-utils && \
    rm -rf /var/lib/apt/lists/*

RUN if [ "$RELEASE_VERSION" = "latest" ]; then \
        curl -L https://github.com/gear-tech/gear/releases/latest/download/gear -o /usr/local/bin/gear && \
        chmod +x /usr/local/bin/gear ; \
    else \
        curl -L https://github.com/gear-tech/gear/releases/download/$RELEASE_VERSION/gear -o /usr/local/bin/gear && \
        chmod +x /usr/local/bin/gear ; \
    fi

RUN gear --version

CMD ["gear"]
