# This file contains settings for `cargo hakari`.
# See https://docs.rs/cargo-hakari/latest/cargo_hakari/config for a full list of options.

hakari-package = "gear-workspace-hack"

# Format version for hakari's output. Version 4 requires cargo-hakari 0.9.22 or above.
dep-format-version = "4"

# Setting workspace.resolver = "2" or higher in the root Cargo.toml is HIGHLY recommended.
# Hakari works much better with the v2 resolver. (The v2 and v3 resolvers are identical from
# hakari's perspective, so you're welcome to set either.)
#
# For more about the new feature resolver, see:
# https://blog.rust-lang.org/2021/03/25/Rust-1.51.0.html#cargos-new-feature-resolver
resolver = "3"

# Add triples corresponding to platforms commonly used by developers here.
# https://doc.rust-lang.org/rustc/platform-support.html
platforms = [
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",
    "aarch64-apple-darwin"
]

# Write out exact versions rather than a semver range. (Defaults to false.)
# exact-versions = true

workspace-hack-line-style = "workspace-dotted"

[final-excludes]
workspace-members = [
    "sc-executor",
    "sc-executor-common",
    "sc-executor-polkavm",
    "sc-executor-wasmtime",
    "sp-allocator",
    "sp-runtime-interface-proc-macro",
    "sp-wasm-interface",
    "sp-wasm-interface-common",
    "substrate-wasm-builder",
]

third-party = [
    # we have to exclude these deps because of their `try-runtime` and `runtime-benchmarks` features,
    # because we cannot, for example, run `cargo build --package gear-cli` without `--all-features` flag
    { name = "frame-benchmarking", git = "https://github.com/paritytech/polkadot-sdk.git", rev = "e3737178ec726cffe506c907263aaaa417893fd0" },
    { name = "frame-benchmarking-cli", git = "https://github.com/paritytech/polkadot-sdk.git", rev = "e3737178ec726cffe506c907263aaaa417893fd0" },
    { name = "frame-election-provider-support", git = "https://github.com/paritytech/polkadot-sdk.git", rev = "e3737178ec726cffe506c907263aaaa417893fd0" },
    { name = "frame-executive", git = "https://github.com/paritytech/polkadot-sdk.git", rev = "e3737178ec726cffe506c907263aaaa417893fd0" },
    { name = "frame-support", git = "https://github.com/paritytech/polkadot-sdk.git", rev = "e3737178ec726cffe506c907263aaaa417893fd0" },
    { name = "frame-system", git = "https://github.com/paritytech/polkadot-sdk.git", rev = "e3737178ec726cffe506c907263aaaa417893fd0" },
    { name = "frame-try-runtime", git = "https://github.com/paritytech/polkadot-sdk.git", rev = "e3737178ec726cffe506c907263aaaa417893fd0" },
    { name = "pallet-authority-discovery", git = "https://github.com/paritytech/polkadot-sdk.git", rev = "e3737178ec726cffe506c907263aaaa417893fd0" },
    { name = "pallet-authorship", git = "https://github.com/paritytech/polkadot-sdk.git", rev = "e3737178ec726cffe506c907263aaaa417893fd0" },
    { name = "pallet-babe", git = "https://github.com/paritytech/polkadot-sdk.git", rev = "e3737178ec726cffe506c907263aaaa417893fd0" },
    { name = "pallet-bags-list", git = "https://github.com/paritytech/polkadot-sdk.git", rev = "e3737178ec726cffe506c907263aaaa417893fd0" },
    { name = "pallet-balances", git = "https://github.com/paritytech/polkadot-sdk.git", rev = "e3737178ec726cffe506c907263aaaa417893fd0" },
    { name = "pallet-bounties", git = "https://github.com/paritytech/polkadot-sdk.git", rev = "e3737178ec726cffe506c907263aaaa417893fd0" },
    { name = "pallet-child-bounties", git = "https://github.com/paritytech/polkadot-sdk.git", rev = "e3737178ec726cffe506c907263aaaa417893fd0" },
    { name = "pallet-conviction-voting", git = "https://github.com/paritytech/polkadot-sdk.git", rev = "e3737178ec726cffe506c907263aaaa417893fd0" },
    { name = "pallet-election-provider-multi-phase", git = "https://github.com/paritytech/polkadot-sdk.git", rev = "e3737178ec726cffe506c907263aaaa417893fd0" },
    { name = "pallet-grandpa", git = "https://github.com/paritytech/polkadot-sdk.git", rev = "e3737178ec726cffe506c907263aaaa417893fd0" },
    { name = "pallet-identity", git = "https://github.com/paritytech/polkadot-sdk.git", rev = "e3737178ec726cffe506c907263aaaa417893fd0" },
    { name = "pallet-im-online", git = "https://github.com/paritytech/polkadot-sdk.git", rev = "e3737178ec726cffe506c907263aaaa417893fd0" },
    { name = "pallet-multisig", git = "https://github.com/paritytech/polkadot-sdk.git", rev = "e3737178ec726cffe506c907263aaaa417893fd0" },
    { name = "pallet-nomination-pools", git = "https://github.com/paritytech/polkadot-sdk.git", rev = "e3737178ec726cffe506c907263aaaa417893fd0" },
    { name = "pallet-offences", git = "https://github.com/paritytech/polkadot-sdk.git", rev = "e3737178ec726cffe506c907263aaaa417893fd0" },
    { name = "pallet-preimage", git = "https://github.com/paritytech/polkadot-sdk.git", rev = "e3737178ec726cffe506c907263aaaa417893fd0" },
    { name = "pallet-proxy", git = "https://github.com/paritytech/polkadot-sdk.git", rev = "e3737178ec726cffe506c907263aaaa417893fd0" },
    { name = "pallet-ranked-collective", git = "https://github.com/paritytech/polkadot-sdk.git", rev = "e3737178ec726cffe506c907263aaaa417893fd0" },
    { name = "pallet-referenda", git = "https://github.com/paritytech/polkadot-sdk.git", rev = "e3737178ec726cffe506c907263aaaa417893fd0" },
    { name = "pallet-scheduler", git = "https://github.com/paritytech/polkadot-sdk.git", rev = "e3737178ec726cffe506c907263aaaa417893fd0" },
    { name = "pallet-session", git = "https://github.com/paritytech/polkadot-sdk.git", rev = "e3737178ec726cffe506c907263aaaa417893fd0" },
    { name = "pallet-staking", git = "https://github.com/paritytech/polkadot-sdk.git", rev = "e3737178ec726cffe506c907263aaaa417893fd0" },
    { name = "pallet-sudo", git = "https://github.com/paritytech/polkadot-sdk.git", rev = "e3737178ec726cffe506c907263aaaa417893fd0" },
    { name = "pallet-timestamp", git = "https://github.com/paritytech/polkadot-sdk.git", rev = "e3737178ec726cffe506c907263aaaa417893fd0" },
    { name = "pallet-transaction-payment", git = "https://github.com/paritytech/polkadot-sdk.git", rev = "e3737178ec726cffe506c907263aaaa417893fd0" },
    { name = "pallet-treasury", git = "https://github.com/paritytech/polkadot-sdk.git", rev = "e3737178ec726cffe506c907263aaaa417893fd0" },
    { name = "pallet-utility", git = "https://github.com/paritytech/polkadot-sdk.git", rev = "e3737178ec726cffe506c907263aaaa417893fd0" },
    { name = "pallet-vesting", git = "https://github.com/paritytech/polkadot-sdk.git", rev = "e3737178ec726cffe506c907263aaaa417893fd0" },
    { name = "pallet-whitelist", git = "https://github.com/paritytech/polkadot-sdk.git", rev = "e3737178ec726cffe506c907263aaaa417893fd0" },
    { name = "sc-cli", git = "https://github.com/paritytech/polkadot-sdk.git", rev = "e3737178ec726cffe506c907263aaaa417893fd0" },
    { name = "sc-client-db", git = "https://github.com/paritytech/polkadot-sdk.git", rev = "e3737178ec726cffe506c907263aaaa417893fd0" },
    { name = "sc-service", git = "https://github.com/paritytech/polkadot-sdk.git", rev = "e3737178ec726cffe506c907263aaaa417893fd0" },
    { name = "sp-runtime", git = "https://github.com/paritytech/polkadot-sdk.git", rev = "e3737178ec726cffe506c907263aaaa417893fd0" },
    { name = "sp-staking", git = "https://github.com/paritytech/polkadot-sdk.git", rev = "e3737178ec726cffe506c907263aaaa417893fd0" },
]
