[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
remappings = [
    "forge-std/=dependencies/forge-std-1.16.2/src/",
    "@openzeppelin/contracts/=dependencies/@openzeppelin-contracts-5.6.1/",
    "@openzeppelin/contracts-upgradeable/=dependencies/@openzeppelin-contracts-upgradeable-5.6.1/",
    "@symbioticfi/core/=dependencies/symbiotic-core-main/",
    "symbiotic-core/=dependencies/symbiotic-core-main/",
    "symbiotic-rewards/=dependencies/symbiotic-rewards-main/",
    "frost-secp256k1-evm/=dependencies/frost-secp256k1-evm-master/src/",
]
evm_version = "osaka"
solc_version = "0.8.35"
optimizer = true
# extra_output_files = ["irOptimized"] # Uncomment to enable saving optimized IR
via_ir = true
bytecode_hash = "none"
cbor_metadata = false
# Required for OpenZeppelin Foundry Upgrades:
# - https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
# Some warnings should be omitted:
# - https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/issues/115
# - https://github.com/OpenZeppelin/openzeppelin-contracts/issues/5577
ignored_warnings_from = [
    "dependencies/openzeppelin-foundry-upgrades-0.4.1/src/internal/Core.sol",
    "dependencies/openzeppelin-foundry-upgrades-0.4.1/src/internal/DefenderDeploy.sol",
    "dependencies/openzeppelin-foundry-upgrades-0.4.1/src/internal/StringFinder.sol",

    "dependencies/@openzeppelin-contracts-5.6.1/utils/cryptography/ECDSA.sol",
    "dependencies/@openzeppelin-contracts-5.6.1/utils/structs/EnumerableMap.sol",
    "dependencies/@openzeppelin-contracts-5.6.1/utils/structs/EnumerableSet.sol",

    "src/Mirror.sol",
    "src/MirrorProxy.sol",
]
# Required for Middleware tests
fs_permissions = [ { access = "read-write", path = "out" }, { access = "read", path = "dependencies" } ]

[dependencies]
forge-std = "1.16.2"
"@openzeppelin-contracts" = "5.6.1"
"@openzeppelin-contracts-upgradeable" = "5.6.1"
openzeppelin-foundry-upgrades = "0.4.1"
symbiotic-core = { version = "main", git = "https://github.com/StackOverflowExcept1on/symbiotic-core.git", branch = "main" }
symbiotic-rewards = { version = "main", git = "https://github.com/StackOverflowExcept1on/symbiotic-rewards.git", branch = "main" }
frost-secp256k1-evm = { version = "master", git = "https://github.com/StackOverflowExcept1on/frost-secp256k1-evm.git", branch = "master" }

[fmt]
sort_imports = true

# Temporary disabled lint rules
[lint]
exclude_lints = ["asm-keccak256"]

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
hoodi = "${HOODI_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
hoodi = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
